### ISSUE TITLE
Command-line tool

### ISSUE THREAD

**Issue by sebastien** [davidmerfield/Typeset#2]
It would be great to have a command line tool to use `typeset` as a post-processor (bearing in mind that `typeset` is sometimes a reserved shell command).

**Comment by davidmerfield** [comment]
This actually [wouldn't be too much work](http://javascriptplayground.com/blog/2015/03/node-command-line-tool/). It would involve extra conditionals to accept arguments passed via the command line, but installation and usage would look something like this:

```
npm install -g cute-files
typeset index.html index-out.html
```

I'd be happy to review a pull request if you'd like to make these modifications yourself – otherwise I'll add it to the list of things to do!

**Comment by sebastien** [comment]
Some recommendations to make the command line tool UNIX-friendly

- use `typeset-js` or something similar as `typeset` is reserved in Bash
- support `-` option for stdin
- by default output to stdout

I don't have much experience with node, but that might be a fun learning experience.

**Comment by davidmerfield** [comment]
Thanks @faheempatel for your pull request. I'll keep this issue open until I work out how to change the tools name from typeset, since it's reserved.

**Comment by davidmerfield** [comment]
I'd also like it accept input via stdin. Will investigate

**Comment by faheempatel** [comment]
No worries :)
You can change the name of the tool by changing the key here: https://github.com/davidmerfield/Typeset/blob/master/package.json#L7
